version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres-latest
    restart: always
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_ROOT_PASSWORD: root@password
      POSTGRES_DB: name-database
    ports:
      - "5433:5432"

  adminer:
    image: adminer
    container_name: adminer-hydra
    restart: always
    ports:
      - "0.0.0.0:8080:8080"
    environment:
      ADMINER_DESIGN: "hydra"

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    hostname: rabbit-server
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data:
    driver: local
